### ISSUE TITLE
Problems to test turner.h

### ISSUE THREAD

**Issue by fraespre** [andydansby/FASE-FN-Balls#1]
Hi Andy,

I didn't know where I can write to ask about your creation (FN Balls).
After read your blog aboun the sounds fx, I would like to test the turner engine to generate sounds. But when I compile with the new library version z88dk, I find several warnings, and when I run the tap in a emulator, the program crash :-(

`Warning at file '../src/./sfx.c' line 518: integer '28748' out of range
Warning at file '../src/./sfx.c' line 521: integer '28749' out of range
Warning at file '../src/./sfx.c' line 524: integer '28750' out of range
Warning at file '../src/./sfx.c' line 527: integer '28751' out of range
Warning at file '../src/./sfx.c' line 530: integer '28752' out of range
Warning at file '../src/./sfx.c' line 537: integer '28753' out of range
Warning at file '../src/./sfx.c' line 540: integer '28754' out of range
Warning at file '../src/./sfx.c' line 543: integer '28755' out of range
type "C:\Users\e104119\AppData\Local\Temp\zccEADB12.map" >> "batsp1.map"
appmake +zx  -b "batsp1" -c "C:\Users\e104119\AppData\Local\Temp\zccEADB12"

Errors in source file C:\mio\install\dev\z80\z88dk-win32-1.99C\ lib\config\\..\..\\libsrc\_DEVELOPMENT\target\zx\zx_crt.asm:
Warning at file '../src/./sfx.c' line 518: integer '28748' out of range
                   ^ ---- (null)Warning at file '../src/./sfx.c' line 521: integer '28749' out of range
                   ^ ---- (null)Warning at file '../src/./sfx.c' line 524: integer '28750' out of range
                   ^ ---- (null)Warning at file '../src/./sfx.c' line 527: integer '28751' out of range
                   ^ ---- (null)Warning at file '../src/./sfx.c' line 530: integer '28752' out of range
                   ^ ---- (null)Warning at file '../src/./sfx.c' line 537: integer '28753' out of range
                   ^ ---- (null)Warning at file '../src/./sfx.c' line 540: integer '28754' out of range
                   ^ ---- (null)Warning at file '../src/./sfx.c' line 543: integer '28755' out of range
                   ^ ---- (null)`

Have you any idea about which could be the problem ?

Thanks in advance,

**Comment by fraespre** [comment]
Here you have the file that I triying to compile:

[sfx.c.txt](https://github.com/andydansby/FASE-FN-Balls/files/3741624/sfx.c.txt)

**Comment by fraespre** [comment]
I've discovered that changing this, the compilation works well:

sonfrq:	defw sfxData
;start frequency		
soncfg:	defw sfxData + 1
;frequency change
sonmod:	defw sfxData+2
;change times
sonlen:	defw sfxData+3
;repeat times
sontyp:	defw sfxData+4
;modulate type
	;0 sawtooth
	;1 2nd mod down
	;2 2nd mod up
	;3+ triangle	
sobrsf:	defw sfxData+5
;reset frequency
sonrnd:	defw sfxData+6
;change reset temp
sonnex:	defw sfxData+7

But, in executin time, my demo crash when I try to play a sound. Really is compatible with z88dk ? Can I enable the IM2, or this could produce problems ?

Thanks again,

**Comment by andydansby** [comment]
It’s not been tested with the latest version of Z88dk at this time is 1.99c, but I have compiled with an old version of Z88dk found at (https://github.com/andydansby/z88dk-MK2)  . Some features may have deprecated in 1.99c. 

Away from the programming pc for a few days but start by commenting out turner.h first and test the rest of the compile. 

edit: just saw that you were compiling with the new library, I had used the classic library.  The compiling string is found in fase.bat

**Comment by andydansby** [comment]
Just a quick look at your sfx.c.txt.  I noticed something slightly different.

your code
void sfx_play(uint8_t fx)

my code 
extern void __FASTCALL__ SFX(unsigned char fx) 

I use the __FASTCALL__ method to have Z88dk restore the stack automatically.  If you do not use the __FASTCALL__ method, you will have to restore the stack manually.

**Comment by fraespre** [comment]
Yeeeeeeeeesssss !!! This was the problem :-p
Now it works without crashes.

In the new version the syntax is a bit different.
[sfx.c.txt](https://github.com/andydansby/FASE-FN-Balls/files/3745947/sfx.c.txt)

A lot of thanks Andy for your help !!!

**Comment by fraespre** [comment]
I take the opportunity to ask you a question:
If this sound engine doesn't use the interruptions, then really it stop the "game" when the sound is playing. However I don't have the feeling it stops (I tested the beepfx and I could clearly feel that stop)

**Comment by andydansby** [comment]
The trick is to keep the effect really short because the game certainly stops during playback. The actual turner sound effect did use interrupts.

**Comment by andydansby** [comment]
I added my contact info on the readme if you want to email me about anything else
